#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Balls
#define ITEM_MASTER_BALL             1
#define ITEM_ULTRA_BALL              2
#define ITEM_GREAT_BALL              3
#define ITEM_POKE_BALL               4
#define ITEM_SAFARI_BALL             5
#define ITEM_NET_BALL                6
#define ITEM_DIVE_BALL               7
#define ITEM_NEST_BALL               8
#define ITEM_REPEAT_BALL             9
#define ITEM_TIMER_BALL             10
#define ITEM_LUXURY_BALL            11
#define ITEM_PREMIER_BALL           12
#define ITEM_LEVEL_BALL             13
#define ITEM_LURE_BALL              14
#define ITEM_MOON_BALL              15
#define ITEM_FRIEND_BALL            16
#define ITEM_LOVE_BALL              17
#define ITEM_HEAVY_BALL             18
#define ITEM_FAST_BALL              19
#define ITEM_SPORT_BALL             20
#define ITEM_HEAL_BALL              21
#define ITEM_QUICK_BALL             22
#define ITEM_DUSK_BALL              23
#define ITEM_CHERISH_BALL           24
#define ITEM_PARK_BALL              25

// Pokémon Items
#define ITEM_POTION                 26
#define ITEM_ANTIDOTE               27
#define ITEM_BURN_HEAL              28
#define ITEM_ICE_HEAL               29
#define ITEM_AWAKENING              30
#define ITEM_PARALYZE_HEAL          31
#define ITEM_FULL_RESTORE           32
#define ITEM_MAX_POTION             33
#define ITEM_HYPER_POTION           34
#define ITEM_SUPER_POTION           35
#define ITEM_FULL_HEAL              36
#define ITEM_REVIVE                 37
#define ITEM_MAX_REVIVE             38
#define ITEM_FRESH_WATER            39
#define ITEM_SODA_POP               40
#define ITEM_LEMONADE               41
#define ITEM_MOOMOO_MILK            42
#define ITEM_ENERGY_POWDER          43
#define ITEM_ENERGY_ROOT            44
#define ITEM_HEAL_POWDER            45
#define ITEM_REVIVAL_HERB           46
#define ITEM_ETHER                  47
#define ITEM_MAX_ETHER              48
#define ITEM_ELIXIR                 49
#define ITEM_MAX_ELIXIR             50
#define ITEM_LAVA_COOKIE            51
#define ITEM_BERRY_JUICE            52
#define ITEM_SACRED_ASH             53
#define ITEM_HP_UP                  54
#define ITEM_PROTEIN                55
#define ITEM_IRON                   56
#define ITEM_CARBOS                 57
#define ITEM_CALCIUM                58
#define ITEM_ZINC                   59
#define ITEM_PP_UP                  60
#define ITEM_PP_MAX                 61
#define ITEM_RARE_CANDY             62
#define ITEM_GUARD_SPEC             63
#define ITEM_DIRE_HIT               64
#define ITEM_X_ATTACK               65
#define ITEM_X_DEFEND               66
#define ITEM_X_SPEED                67
#define ITEM_X_ACCURACY             68
#define ITEM_X_SPECIAL              69
#define ITEM_X_SPECIAL_DEFENSE      70
#define ITEM_POKE_DOLL              71
#define ITEM_FLUFFY_TAIL            72
#define ITEM_BLUE_FLUTE             73
#define ITEM_YELLOW_FLUTE           74
#define ITEM_RED_FLUTE              75
#define ITEM_BLACK_FLUTE            76
#define ITEM_WHITE_FLUTE            77
#define ITEM_SHOAL_SALT             78
#define ITEM_SHOAL_SHELL            79
#define ITEM_RED_SHARD              80
#define ITEM_BLUE_SHARD             81
#define ITEM_YELLOW_SHARD           82
#define ITEM_GREEN_SHARD            83
#define ITEM_REPEL                  84
#define ITEM_SUPER_REPEL            85
#define ITEM_MAX_REPEL              86
#define ITEM_ESCAPE_ROPE            87
#define ITEM_SUN_STONE              88
#define ITEM_MOON_STONE             89
#define ITEM_FIRE_STONE             90
#define ITEM_THUNDER_STONE          91
#define ITEM_WATER_STONE            92
#define ITEM_LEAF_STONE             93
#define ITEM_DAWN_STONE             94
#define ITEM_DUSK_STONE             95
#define ITEM_SHINY_STONE            96

// Mails
#define ITEM_ORANGE_MAIL            97
#define ITEM_HARBOR_MAIL            98
#define ITEM_GLITTER_MAIL           99
#define ITEM_MECH_MAIL             100
#define ITEM_WOOD_MAIL             101
#define ITEM_WAVE_MAIL             102
#define ITEM_BEAD_MAIL             103
#define ITEM_SHADOW_MAIL           104
#define ITEM_TROPIC_MAIL           105
#define ITEM_DREAM_MAIL            106
#define ITEM_FAB_MAIL              107
#define ITEM_RETRO_MAIL            108

// Berries
#define ITEM_CHERI_BERRY           109
#define ITEM_CHESTO_BERRY          110
#define ITEM_PECHA_BERRY           111
#define ITEM_RAWST_BERRY           112
#define ITEM_ASPEAR_BERRY          113
#define ITEM_LEPPA_BERRY           114
#define ITEM_ORAN_BERRY            115
#define ITEM_PERSIM_BERRY          116
#define ITEM_LUM_BERRY             117
#define ITEM_SITRUS_BERRY          118
#define ITEM_FIGY_BERRY            119
#define ITEM_WIKI_BERRY            120
#define ITEM_MAGO_BERRY            121
#define ITEM_AGUAV_BERRY           122
#define ITEM_IAPAPA_BERRY          123
#define ITEM_RAZZ_BERRY            124
#define ITEM_BLUK_BERRY            125
#define ITEM_NANAB_BERRY           126
#define ITEM_WEPEAR_BERRY          127
#define ITEM_PINAP_BERRY           128
#define ITEM_POMEG_BERRY           129
#define ITEM_KELPSY_BERRY          130
#define ITEM_QUALOT_BERRY          131
#define ITEM_HONDEW_BERRY          132
#define ITEM_GREPA_BERRY           133
#define ITEM_TAMATO_BERRY          134
#define ITEM_CORNN_BERRY           135
#define ITEM_MAGOST_BERRY          136 
#define ITEM_RABUTA_BERRY          137
#define ITEM_NOMEL_BERRY           138
#define ITEM_SPELON_BERRY          139
#define ITEM_PAMTRE_BERRY          140
#define ITEM_WATMEL_BERRY          141
#define ITEM_DURIN_BERRY           142
#define ITEM_BELUE_BERRY           143
#define ITEM_LIECHI_BERRY          144
#define ITEM_GANLON_BERRY          145
#define ITEM_SALAC_BERRY           146
#define ITEM_PETAYA_BERRY          147
#define ITEM_APICOT_BERRY          148
#define ITEM_LANSAT_BERRY          149
#define ITEM_STARF_BERRY           150
#define ITEM_ENIGMA_BERRY          151
#define ITEM_OCCA_BERRY            152
#define ITEM_PASSHO_BERRY          153
#define ITEM_WACAN_BERRY           154
#define ITEM_RINDO_BERRY           155
#define ITEM_YACHE_BERRY           156
#define ITEM_CHOPLE_BERRY          157
#define ITEM_KEBIA_BERRY           158
#define ITEM_SHUCA_BERRY           159
#define ITEM_COBA_BERRY            160
#define ITEM_PAYAPA_BERRY          161
#define ITEM_TANGA_BERRY           162
#define ITEM_CHARTI_BERRY          163
#define ITEM_KASIB_BERRY           164
#define ITEM_HABAN_BERRY           165
#define ITEM_COLBUR_BERRY          166
#define ITEM_BABIRI_BERRY          167
#define ITEM_CHILAN_BERRY          168
#define ITEM_MICLE_BERRY           169
#define ITEM_CUSTAP_BERRY          170
#define ITEM_JABOCA_BERRY          171
#define ITEM_ROWAP_BERRY           172

// Apricorns
#define ITEM_RED_APRICORN          173
#define ITEM_BLUE_APRICORN         174
#define ITEM_YELLOW_APRICORN       175
#define ITEM_GREEN_APRICORN        176
#define ITEM_PINK_APRICORN         177
#define ITEM_WHITE_APRICORN        178
#define ITEM_BLACK_APRICORN        179

// Hold and Miscellaneous Items
#define ITEM_BRIGHT_POWDER         180
#define ITEM_WHITE_HERB            181
#define ITEM_MACHO_BRACE           182
#define ITEM_EXP_SHARE             183
#define ITEM_QUICK_CLAW            184
#define ITEM_SOOTHE_BELL           185
#define ITEM_MENTAL_HERB           186
#define ITEM_CHOICE_BAND           187
#define ITEM_KINGS_ROCK            188
#define ITEM_SILVER_POWDER         189
#define ITEM_AMULET_COIN           190
#define ITEM_CLEANSE_TAG           191
#define ITEM_SOUL_DEW              192
#define ITEM_DEEP_SEA_TOOTH        193
#define ITEM_DEEP_SEA_SCALE        194
#define ITEM_SMOKE_BALL            195
#define ITEM_EVERSTONE             196
#define ITEM_FOCUS_BAND            197
#define ITEM_LUCKY_EGG             198
#define ITEM_SCOPE_LENS            199
#define ITEM_METAL_COAT            200
#define ITEM_LEFTOVERS             201
#define ITEM_DRAGON_SCALE          202
#define ITEM_LIGHT_BALL            203
#define ITEM_SOFT_SAND             204
#define ITEM_HARD_STONE            205
#define ITEM_MIRACLE_SEED          206
#define ITEM_BLACK_GLASSES         207
#define ITEM_BLACK_BELT            208
#define ITEM_MAGNET                209
#define ITEM_MYSTIC_WATER          210
#define ITEM_SHARP_BEAK            211
#define ITEM_POISON_BARB           212
#define ITEM_NEVER_MELT_ICE        213
#define ITEM_SPELL_TAG             214
#define ITEM_TWISTED_SPOON         215
#define ITEM_CHARCOAL              216
#define ITEM_DRAGON_FANG           217
#define ITEM_SILK_SCARF            218
#define ITEM_UP_GRADE              219
#define ITEM_SHELL_BELL            220
#define ITEM_SEA_INCENSE           221
#define ITEM_LAX_INCENSE           222
#define ITEM_LUCKY_PUNCH           223
#define ITEM_METAL_POWDER          224
#define ITEM_THICK_CLUB            225
#define ITEM_STICK                 226
#define ITEM_RED_SCARF             227
#define ITEM_BLUE_SCARF            228
#define ITEM_PINK_SCARF            229
#define ITEM_GREEN_SCARF           230
#define ITEM_YELLOW_SCARF          231
#define ITEM_WIDE_LENS             232
#define ITEM_MUSCLE_BAND           233
#define ITEM_WISE_GLASSES          234
#define ITEM_EXPERT_BELT           235
#define ITEM_LIGHT_CLAY            236
#define ITEM_POWER_HERB            237
#define ITEM_LIFE_ORB              238
#define ITEM_FLAME_ORB             239
#define ITEM_TOXIC_ORB             240
#define ITEM_QUICK_POWDER          241
#define ITEM_FOCUS_SASH            242
#define ITEM_ZOOM_LENS             243
#define ITEM_METRONOME             244
#define ITEM_IRON_BALL             245
#define ITEM_LAGGING_TAIL          246
#define ITEM_DESTINY_KNOT          247
#define ITEM_BLACK_SLUDGE          248
#define ITEM_ICY_ROCK              249
#define ITEM_SMOOTH_ROCK           250
#define ITEM_HEAT_ROCK             251
#define ITEM_DAMP_ROCK             252
#define ITEM_GRIP_CLAW             253
#define ITEM_CHOICE_SCARF          254
#define ITEM_STICKY_BARB           255
#define ITEM_POWER_WEIGHT          256
#define ITEM_POWER_BRACER          257
#define ITEM_POWER_BELT            258
#define ITEM_POWER_ANKLET          259
#define ITEM_POWER_LENS            260
#define ITEM_POWER_BAND            261
#define ITEM_SHED_SHELL            262
#define ITEM_BIG_ROOT              263
#define ITEM_CHOICE_SPECS          264
#define ITEM_DRACO_PLATE           265
#define ITEM_DREAD_PLATE           266
#define ITEM_EARTH_PLATE           267
#define ITEM_FIST_PLATE            268
#define ITEM_FLAME_PLATE           269
#define ITEM_ICICLE_PLATE          270
#define ITEM_INSECT_PLATE          271
#define ITEM_IRON_PLATE            272
#define ITEM_MEADOW_PLATE          273
#define ITEM_MIND_PLATE            274
#define ITEM_SKY_PLATE             275
#define ITEM_SPLASH_PLATE          276
#define ITEM_SPOOKY_PLATE          277
#define ITEM_STONE_PLATE           278
#define ITEM_TOXIC_PLATE           279
#define ITEM_ZAP_PLATE             280
#define ITEM_FULL_INCENSE          281
#define ITEM_LUCK_INCENSE          282
#define ITEM_ODD_INCENSE           283
#define ITEM_PURE_INCENSE          284
#define ITEM_ROCK_INCENSE          285
#define ITEM_ROSE_INCENSE          286
#define ITEM_WAVE_INCENSE          287
#define ITEM_OVAL_STONE            288
#define ITEM_PROTECTOR             289
#define ITEM_ELECTIRIZER           290
#define ITEM_MAGMARIZER            291
#define ITEM_DUBIOUS_DISC          292
#define ITEM_REAPER_CLOTH          293
#define ITEM_RAZOR_CLAW            294
#define ITEM_RAZOR_FANG            295
#define ITEM_TINY_MUSHROOM         296
#define ITEM_BIG_MUSHROOM          297
#define ITEM_PEARL                 298
#define ITEM_BIG_PEARL             299
#define ITEM_STARDUST              300
#define ITEM_STAR_PIECE            301
#define ITEM_NUGGET                302
#define ITEM_HEART_SCALE           303
#define ITEM_HONEY                 304
#define ITEM_ODD_KEYSTONE          305
#define ITEM_ADAMANT_ORB           306
#define ITEM_LUSTROUS_ORB          307
#define ITEM_GRISEOUS_ORB          308

// TMs/HMs
#define ITEM_TM01_FOCUS_PUNCH      309
#define ITEM_TM02_DRAGON_CLAW      310
#define ITEM_TM03_WATER_PULSE      311
#define ITEM_TM04_CALM_MIND        312
#define ITEM_TM05_ROAR             313
#define ITEM_TM06_TOXIC            314
#define ITEM_TM07_HAIL             315
#define ITEM_TM08_BULK_UP          316
#define ITEM_TM09_BULLET_SEED      317
#define ITEM_TM10_HIDDEN_POWER     318
#define ITEM_TM11_SUNNY_DAY        319
#define ITEM_TM12_TAUNT            320
#define ITEM_TM13_ICE_BEAM         321
#define ITEM_TM14_BLIZZARD         322
#define ITEM_TM15_HYPER_BEAM       323
#define ITEM_TM16_LIGHT_SCREEN     324
#define ITEM_TM17_PROTECT          325
#define ITEM_TM18_RAIN_DANCE       326
#define ITEM_TM19_GIGA_DRAIN       327
#define ITEM_TM20_SAFEGUARD        328
#define ITEM_TM21_FRUSTRATION      329
#define ITEM_TM22_SOLARBEAM        330
#define ITEM_TM23_IRON_TAIL        331
#define ITEM_TM24_THUNDERBOLT      332
#define ITEM_TM25_THUNDER          333
#define ITEM_TM26_EARTHQUAKE       334
#define ITEM_TM27_RETURN           335
#define ITEM_TM28_DIG              336
#define ITEM_TM29_PSYCHIC          337
#define ITEM_TM30_SHADOW_BALL      338
#define ITEM_TM31_BRICK_BREAK      339
#define ITEM_TM32_DOUBLE_TEAM      340
#define ITEM_TM33_REFLECT          341
#define ITEM_TM34_SHOCK_WAVE       342
#define ITEM_TM35_FLAMETHROWER     343
#define ITEM_TM36_SLUDGE_BOMB      344
#define ITEM_TM37_SANDSTORM        345
#define ITEM_TM38_FIRE_BLAST       346
#define ITEM_TM39_ROCK_TOMB        347
#define ITEM_TM40_AERIAL_ACE       348
#define ITEM_TM41_TORMENT          349
#define ITEM_TM42_FACADE           350
#define ITEM_TM43_SECRET_POWER     351
#define ITEM_TM44_REST             352
#define ITEM_TM45_ATTRACT          353
#define ITEM_TM46_THIEF            354
#define ITEM_TM47_STEEL_WING       355
#define ITEM_TM48_SKILL_SWAP       356
#define ITEM_TM49_SNATCH           357
#define ITEM_TM50_OVERHEAT         358
#define ITEM_TM51_ROOST            359
#define ITEM_TM52_FOCUS_BLAST      360
#define ITEM_TM53_ENERGY_BALL      361
#define ITEM_TM54_FALSE_SWIPE      362
#define ITEM_TM55_BRINE            363
#define ITEM_TM56_FLING            364
#define ITEM_TM57_CHARGE_BEAM      365
#define ITEM_TM58_ENDURE           366
#define ITEM_TM59_DRAGON_PULSE     367
#define ITEM_TM60_DRAIN_PUNCH      368
#define ITEM_TM61_WILL_O_WISP      369
#define ITEM_TM62_SILVER_WIND      370
#define ITEM_TM63_EMBARGO          371
#define ITEM_TM64_EXPLOSION        372
#define ITEM_TM65_SHADOW_CLAW      373
#define ITEM_TM66_PAYBACK          374
#define ITEM_TM67_RECYCLE          375
#define ITEM_TM68_GIGA_IMPACT      376
#define ITEM_TM69_ROCK_POLISH      377
#define ITEM_TM70_FLASH            378
#define ITEM_TM71_STONE_EDGE       379
#define ITEM_TM72_AVALANCHE        380
#define ITEM_TM73_THUNDER_WAVE     381
#define ITEM_TM74_GYRO_BALL        382
#define ITEM_TM75_SWORDS_DANCE     383
#define ITEM_TM76_STEALTH_ROCK     384
#define ITEM_TM77_PSYCH_UP         385
#define ITEM_TM78_CAPTIVATE        386
#define ITEM_TM79_DARK_PULSE       387
#define ITEM_TM80_ROCK_SLIDE       388
#define ITEM_TM81_X_SCISSOR        389
#define ITEM_TM82_SLEEP_TALK       390
#define ITEM_TM83_NATURAL_GIFT     391
#define ITEM_TM84_POISON_JAB       392
#define ITEM_TM85_DREAM_EATER      393
#define ITEM_TM86_GRASS_KNOT       394
#define ITEM_TM87_SWAGGER          395
#define ITEM_TM88_PLUCK            396
#define ITEM_TM89_U_TURN           397
#define ITEM_TM90_SUBSTITUTE       398
#define ITEM_TM91_FLASH_CANNON     399
#define ITEM_TM92_TRICK_ROOM       400
#define ITEM_HM01_CUT              401
#define ITEM_HM02_FLY              402
#define ITEM_HM03_SURF             403
#define ITEM_HM04_STRENGTH         404
#define ITEM_HM05_FLASH            405
#define ITEM_HM06_ROCK_SMASH       406
#define ITEM_HM07_WATERFALL        407
#define ITEM_HM08_DIVE             408

// Alternative labels for the TMs/HMs, because it's easier to do "giveitem ITEM_TM01, 1" than "giveitem ITEM_TM01_FOCUS_PUNCH, 1"
#define ITEM_TM01                  ITEM_TM01_FOCUS_PUNCH
#define ITEM_TM02                  ITEM_TM02_DRAGON_CLAW
#define ITEM_TM03                  ITEM_TM03_WATER_PULSE
#define ITEM_TM04                  ITEM_TM04_CALM_MIND
#define ITEM_TM05                  ITEM_TM05_ROAR
#define ITEM_TM06                  ITEM_TM06_TOXIC
#define ITEM_TM07                  ITEM_TM07_HAIL
#define ITEM_TM08                  ITEM_TM08_BULK_UP
#define ITEM_TM09                  ITEM_TM09_BULLET_SEED
#define ITEM_TM10                  ITEM_TM10_HIDDEN_POWER
#define ITEM_TM11                  ITEM_TM11_SUNNY_DAY
#define ITEM_TM12                  ITEM_TM12_TAUNT
#define ITEM_TM13                  ITEM_TM13_ICE_BEAM
#define ITEM_TM14                  ITEM_TM14_BLIZZARD
#define ITEM_TM15                  ITEM_TM15_HYPER_BEAM
#define ITEM_TM16                  ITEM_TM16_LIGHT_SCREEN
#define ITEM_TM17                  ITEM_TM17_PROTECT
#define ITEM_TM18                  ITEM_TM18_RAIN_DANCE
#define ITEM_TM19                  ITEM_TM19_GIGA_DRAIN
#define ITEM_TM20                  ITEM_TM20_SAFEGUARD
#define ITEM_TM21                  ITEM_TM21_FRUSTRATION
#define ITEM_TM22                  ITEM_TM22_SOLARBEAM
#define ITEM_TM23                  ITEM_TM23_IRON_TAIL
#define ITEM_TM24                  ITEM_TM24_THUNDERBOLT
#define ITEM_TM25                  ITEM_TM25_THUNDER
#define ITEM_TM26                  ITEM_TM26_EARTHQUAKE
#define ITEM_TM27                  ITEM_TM27_RETURN
#define ITEM_TM28                  ITEM_TM28_DIG
#define ITEM_TM29                  ITEM_TM29_PSYCHIC
#define ITEM_TM30                  ITEM_TM30_SHADOW_BALL
#define ITEM_TM31                  ITEM_TM31_BRICK_BREAK
#define ITEM_TM32                  ITEM_TM32_DOUBLE_TEAM
#define ITEM_TM33                  ITEM_TM33_REFLECT
#define ITEM_TM34                  ITEM_TM34_SHOCK_WAVE
#define ITEM_TM35                  ITEM_TM35_FLAMETHROWER
#define ITEM_TM36                  ITEM_TM36_SLUDGE_BOMB
#define ITEM_TM37                  ITEM_TM37_SANDSTORM
#define ITEM_TM38                  ITEM_TM38_FIRE_BLAST
#define ITEM_TM39                  ITEM_TM39_ROCK_TOMB
#define ITEM_TM40                  ITEM_TM40_AERIAL_ACE
#define ITEM_TM41                  ITEM_TM41_TORMENT
#define ITEM_TM42                  ITEM_TM42_FACADE
#define ITEM_TM43                  ITEM_TM43_SECRET_POWER
#define ITEM_TM44                  ITEM_TM44_REST
#define ITEM_TM45                  ITEM_TM45_ATTRACT
#define ITEM_TM46                  ITEM_TM46_THIEF
#define ITEM_TM47                  ITEM_TM47_STEEL_WING
#define ITEM_TM48                  ITEM_TM48_SKILL_SWAP
#define ITEM_TM49                  ITEM_TM49_SNATCH
#define ITEM_TM50                  ITEM_TM50_OVERHEAT
#define ITEM_TM51                  ITEM_TM51_ROOST
#define ITEM_TM52                  ITEM_TM52_FOCUS_BLAST
#define ITEM_TM53                  ITEM_TM53_ENERGY_BALL
#define ITEM_TM54                  ITEM_TM54_FALSE_SWIPE
#define ITEM_TM55                  ITEM_TM55_BRINE
#define ITEM_TM56                  ITEM_TM56_FLING
#define ITEM_TM57                  ITEM_TM57_CHARGE_BEAM
#define ITEM_TM58                  ITEM_TM58_ENDURE
#define ITEM_TM59                  ITEM_TM59_DRAGON_PULSE
#define ITEM_TM60                  ITEM_TM60_DRAIN_PUNCH
#define ITEM_TM61                  ITEM_TM61_WILL_O_WISP
#define ITEM_TM62                  ITEM_TM62_SILVER_WIND
#define ITEM_TM63                  ITEM_TM63_EMBARGO
#define ITEM_TM64                  ITEM_TM64_EXPLOSION
#define ITEM_TM65                  ITEM_TM65_SHADOW_CLAW
#define ITEM_TM66                  ITEM_TM66_PAYBACK
#define ITEM_TM67                  ITEM_TM67_RECYCLE
#define ITEM_TM68                  ITEM_TM68_GIGA_IMPACT
#define ITEM_TM69                  ITEM_TM69_ROCK_POLISH
#define ITEM_TM70                  ITEM_TM70_FLASH
#define ITEM_TM71                  ITEM_TM71_STONE_EDGE
#define ITEM_TM72                  ITEM_TM72_AVALANCHE
#define ITEM_TM73                  ITEM_TM73_THUNDER_WAVE
#define ITEM_TM74                  ITEM_TM74_GYRO_BALL
#define ITEM_TM75                  ITEM_TM75_SWORDS_DANCE
#define ITEM_TM76                  ITEM_TM76_STEALTH_ROCK
#define ITEM_TM77                  ITEM_TM77_PSYCH_UP
#define ITEM_TM78                  ITEM_TM78_CAPTIVATE
#define ITEM_TM79                  ITEM_TM79_DARK_PULSE
#define ITEM_TM80                  ITEM_TM80_ROCK_SLIDE
#define ITEM_TM81                  ITEM_TM81_X_SCISSOR
#define ITEM_TM82                  ITEM_TM82_SLEEP_TALK
#define ITEM_TM83                  ITEM_TM83_NATURAL_GIFT
#define ITEM_TM84                  ITEM_TM84_POISON_JAB
#define ITEM_TM85                  ITEM_TM85_DREAM_EATER
#define ITEM_TM86                  ITEM_TM86_GRASS_KNOT
#define ITEM_TM87                  ITEM_TM87_SWAGGER
#define ITEM_TM88                  ITEM_TM88_PLUCK
#define ITEM_TM89                  ITEM_TM89_U_TURN
#define ITEM_TM90                  ITEM_TM90_SUBSTITUTE
#define ITEM_TM91                  ITEM_TM91_FLASH_CANNON
#define ITEM_TM92                  ITEM_TM92_TRICK_ROOM
#define ITEM_HM01                  ITEM_HM01_CUT
#define ITEM_HM02                  ITEM_HM02_FLY
#define ITEM_HM03                  ITEM_HM03_SURF
#define ITEM_HM04                  ITEM_HM04_STRENGTH
#define ITEM_HM05                  ITEM_HM05_FLASH
#define ITEM_HM06                  ITEM_HM06_ROCK_SMASH
#define ITEM_HM07                  ITEM_HM07_WATERFALL
#define ITEM_HM08                  ITEM_HM08_DIVE

#define NUM_TECHNICAL_MACHINES      92
#define NUM_HIDDEN_MACHINES          8

// Key Items
#define ITEM_MACH_BIKE             409
#define ITEM_COIN_CASE             410
#define ITEM_ITEMFINDER            411
#define ITEM_OLD_ROD               412
#define ITEM_GOOD_ROD              413
#define ITEM_SUPER_ROD             414
#define ITEM_SS_TICKET             415
#define ITEM_CONTEST_PASS          416
#define ITEM_WAILMER_PAIL          417
#define ITEM_DEVON_GOODS           418
#define ITEM_SOOT_SACK             419
#define ITEM_BASEMENT_KEY          420
#define ITEM_ACRO_BIKE             421
#define ITEM_POKEBLOCK_CASE        422
#define ITEM_LETTER                423
#define ITEM_EON_TICKET            424
#define ITEM_RED_ORB               425
#define ITEM_BLUE_ORB              426
#define ITEM_SCANNER               427
#define ITEM_GO_GOGGLES            428
#define ITEM_METEORITE             429
#define ITEM_ROOM_1_KEY            430
#define ITEM_ROOM_2_KEY            431
#define ITEM_ROOM_4_KEY            432
#define ITEM_ROOM_6_KEY            433
#define ITEM_STORAGE_KEY           434
#define ITEM_DOME_FOSSIL           435
#define ITEM_HELIX_FOSSIL          436
#define ITEM_OLD_AMBER             437
#define ITEM_CLAW_FOSSIL           438
#define ITEM_ROOT_FOSSIL           439
#define ITEM_ARMOR_FOSSIL          440
#define ITEM_SKULL_FOSSIL          441
#define ITEM_DEVON_SCOPE           442

#define NUM_OF_ITEMS 443

// Check if the item is one that can be used on a Pokemon.
#define IS_POKEMON_ITEM(item) ((item) >= ITEM_POTION && (item) <= ITEM_ROWAP_BERRY)

// Check if the item is a vitamin.
#define IS_ITEM_VITAMIN(item) ((item) >= ITEM_HP_UP && (item) <= ITEM_ZINC)

// Check if the item is a mail.
#define IS_ITEM_MAIL(item) ((item) >= ITEM_ORANGE_MAIL && (item) <= ITEM_RETRO_MAIL)

// Check if the item is a TM or an HM.
#define IS_ITEM_TM(item) ((item) >= ITEM_TM01_FOCUS_PUNCH && (item) <= ITEM_HM08_DIVE)

// Check if the item is a Plate.
#define IS_ITEM_PLATE(item) ((item) >= ITEM_DRACO_PLATE && (item) <= ITEM_ZAP_PLATE)

#endif  // GUARD_CONSTANTS_ITEMS_H
